# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912a1fcdd36fe571adc596ba48f8eeb16bfe9a5b276dad919c0e7d3e7537560d22682415556839e9658a0b7b808fd763c7f8572e6ed892a84a6d8e6aefa5c8a2

test:
  secret_key_base: acca10e11fadcc9c3aa165106ca10f332fca796027a00156aae3f7f2cea614af6a364a8071fcf5cba7af9a2302b048cc386802d789328a1a97d6fb5825ce09ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
